default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: urvashi
  password: 123456

development:
  <<: *default
  database: AppointmentManagementSystem_development

test:
  <<: *default
  database: AppointmentManagementSystem_test

production:
  <<: *default
  database: AppointmentManagementSystem_production
  username: AppointmentManagementSystem
  password: <%= ENV['APPOINTMENTMANAGEMENTSYSTEM_DATABASE_PASSWORD'] %>
